![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(0, 10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(my_array[-1::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [33]:
ej_4 = np.arange(1, 21)
ej_4 = np.reshape(ej_4, (4, 5))
print(ej_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
#Metodo 1
ej_4[::-1][::-1]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
ej_4 = ej_4[::-1, ::-1]
print(ej_4)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [15]:
#Metodo 2 con funciones
ej_4_2 = np.flip(ej_4, axis= 0)
print(ej_4_2)
print("-" * 10)
ej_4_2 = np.flip(ej_4_2, axis= 1)
print(ej_4_2)

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
----------
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [18]:
#Desde ej_4 invertido
print(ej_4[-1:-3:-1, -1:-3:-1])

[[1 2]
 [6 7]]


In [25]:
#Desde ej_4 sin invertir
ej_4[:2, :2]

array([[20, 19],
       [15, 14]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [27]:
#Con matriz ej_4 inv
print(ej_4[-1::-2, -1::-2])

array([[ 1,  3,  5],
       [11, 13, 15]])

In [28]:
#Con matriz sin invertir
print(ej_4[0:3:2, 0:5:2])

[[20 18 16]
 [10  8  6]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [32]:
#Matriz inv
ej_4[-1:0:-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [40]:
#Matriz sin invertir
print(ej_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [48]:
#Matriz sin invertir
print(ej_4[0:-1:1, 5::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [50]:
#Metodo 1
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[x == "Loro"])

['Loro' 'Loro']


In [55]:
#Metodo 2
mask = x == "Loro"
print(x[mask])

['Loro' 'Loro']


In [51]:
#Metodo 3
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
filtrado = filter(lambda x: x=="Loro", x)
print(list(filtrado))

['Loro', 'Loro']


In [57]:
# Con slicing
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[::3])


['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [58]:
ej_9 = np.arange(0, 20)
ej_9 = np.reshape(ej_9, (2, 5, 2))
print(ej_9)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [61]:
print(ej_4[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [66]:
ej_11 = np.zeros(10)
print(ej_11)
print(ej_11.nbytes)
print(ej_11.itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
8


In [65]:
ej_11[3] = 1
print(ej_11)
print(ej_11.nbytes)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
80


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [67]:
ej_12 = np.arange(10, 50)
print(ej_12[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [81]:
#Metodo 1
ej_13 = np.array([1,2,0,0,4,0])
print(np.nonzero(ej_13))

(array([0, 1, 4], dtype=int64),)


In [82]:
#Metodo 2
np.where(ej_13 != 0)[0]

array([0, 1, 4], dtype=int64)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [84]:
ej_15 = np.random.randint(0, 30, 30)
print(ej_15)

[14  3 13 25 25 22  7 22 24 19 27  5 12 21  5  1 29 19 18 15 27  6 27  5
  4 19  4 22 24  1]


In [86]:
media_ej_15 = np.mean(ej_15)
print(media_ej_15)

15.5


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [105]:
#Metodo 1
ej_16 = np.zeros((5, 5))
ej_16[::len(ej_16) - 1] = 1
ej_16[::, ::len(ej_16) - 1] = 1
print(ej_16)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [106]:
#Metodo 2
todoceros = np.zeros((10,10))

todoceros[0]=1
todoceros[-1]=1
todoceros[:,0]=1
todoceros[:,-1]=1

print(todoceros)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [114]:
#Metodo 1
ej_17 = np.ones((8, 8))
ej_17[1::2, 1::2] = 0
ej_17[::2, ::2] = 0
print(ej_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [116]:
#Metodo 2
ej_17 = np.zeros((8, 8))
ej_17[::2, 1::2] = 1
ej_17[1::2, ::2] = 1
print(ej_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [119]:
ej_17 = np.zeros((8, 8))
print(ej_17)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [120]:
#Metodo 3

for i in range(len(ej_17)):
    for j in range(len(ej_17)):
        if (i % 2 == 0  and j % 2 != 0) or (i % 2 != 0  and j % 2 == 0):
            ej_17[i, j] = 1

print(ej_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [126]:
#Metodo 1
array = ej_17[:2]
ej_18 = np.tile(array, (4, 1))
print(ej_18)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [133]:
#Metodo 2
array = [[0, 1], [1, 0]]
ej_18 = np.tile(array, (4, 4))
print(ej_18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [134]:
ej_19 = np.random.randint(0, 25, (5, 5))
print(ej_19)

[[17 13  2  5  6]
 [24  1 23 13 21]
 [ 0 19  6  8  3]
 [18  4 14  2  8]
 [ 8  1 17 20  0]]


In [135]:
ej_19_n = (ej_19 - np.mean(ej_19)) / np.std(ej_19)
print(ej_19_n)

[[ 0.88624479  0.37098619 -1.04597496 -0.65953101 -0.53071636]
 [ 1.78794734 -1.17478961  1.65913269  0.37098619  1.40150339]
 [-1.30360426  1.14387409 -0.53071636 -0.27308706 -0.91716031]
 [ 1.01505944 -0.78834566  0.49980084 -1.04597496 -0.27308706]
 [-0.27308706 -1.17478961  0.88624479  1.27268874 -1.30360426]]


In [136]:
print(np.std(ej_19))
print(np.std(ej_19_n))

7.7630921674291615
0.9999999999999999


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [169]:
ej_20 = np.arange(1, 11)
print(ej_20)

[ 1  2  3  4  5  6  7  8  9 10]


In [170]:
ej_20_2 = ej_20[:]
ej_20_3 = ej_20[:]

In [145]:
ej_20_2[(ej_20_2 > 3) & (ej_20_2 < 8)] = -1
print(ej_20_2)

[ 1  2  3 -1 -1 -1 -1  8  9 10]


In [151]:
#Metodo 1
ej_20_3[(ej_20_2 > 3) & (ej_20_2 < 8)] = ej_20_3[(ej_20_2 > 3) & (ej_20_2 < 8)] * -1
print(ej_20_3)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


In [157]:
#Metodo 2
array21= np.where((ej_20 > 3) & (ej_20 < 8), False, ej_20)
print(array21)

[ 1  2  3  0  0  0  0  8  9 10]


In [163]:
#Metodo 3

nuevo_array_negado = np.where(np.logical_and(ej_20 > 3, ej_20 < 8), - ej_20, ej_20)
print("Nuevo array negado entre 3 y 8:", nuevo_array_negado)

Nuevo array negado entre 3 y 8: [ 1  2  3 -4 -5 -6 -7  8  9 10]


In [171]:
#Metodo 4

ej_20_3[3:-3] = -1
print(ej_20_3)

[ 1  2  3 -1 -1 -1 -1  8  9 10]
